### PR TITLE
Enable C#12

### PR DESCRIPTION
**Pull request by colombod**
Complete .NET8 release with C#12 support

### CODE REVIEW

**Comment by johngardner58work** [comment]
Error: (4,22): error CS1002: ; expected

**Comment by colombod** [comment]
Using statement are not supported in csharp scripting, they won't work

**Comment by jonsequitur** [comment]
@johngardner58work Is it your expectation that disposal would happen when the kernel is shut down (i.e. when you restart it or close the notebook)?

If so you can do this:

```csharp
Microsoft.DotNet.Interactive.Kernel.Root.RegisterForDisposal(factory);
```

**Comment by jonsequitur** [comment]
> Perhaps I should repost for Csharp scripting?

The place to open this issue would be in [dotnet/roslyn](https://github.com/dotnet/roslyn/issues).

**Pull request merged**
