### PR TITLE
fix CustomMimeType parameter

### PR DESCRIPTION
**Pull request by eosfor**
hopefully this time i fixed the formatting issue. vscode was "autoformatting on save"

### CODE REVIEW

**Comment by eosfor** [comment]
@jonsequitur, I had to cancel my previous PRs. Initially I was not able to figure out what was happening with formatting, and then just luckily sopped how VSCode "auto-formatted" on save. Hopefully it works this time

**Comment by jonsequitur** [comment]
Thanks!

This looks better. 

One thing that I might not have been clear about is that removing the `CustomMimeType` property entirely, and just using `MimeType`, would be better still. The extra concept makes things harder to understand, and the `MimeType` property shouldn't be restricted to just a few types. It's intended to open-ended and this is how it works everywhere else in .NET Interactive.

**Comment by eosfor** [comment]
> Thanks!
> 
> This looks better.
> 
> One thing that I might not have been clear about is that removing the `CustomMimeType` property entirely, and just using `MimeType`, would be better still. The extra concept makes things harder to understand, and the `MimeType` property shouldn't be restricted to just a few types. It's intended to open-ended and this is how it works everywhere else in .NET Interactive.

Well, I agree, but for some reason someone did split them into two different options. And behavior is totally different, as far as I understand. What was the reason for splitting them?

**Comment by eosfor** [comment]
@jonsequitur this time I removed CustomMimeType parameter completely

**Review by jonsequitur — APPROVED** [review]

**Comment by jonsequitur** [comment]
Thanks, @eosfor!

**Pull request merged**
