### PR TITLE
amend cursor position decrement logic & create language service command kernel test

### PR DESCRIPTION
**Pull request by cartercanedy**
### Changes:
* Refactored the logic around cursor position decrement to skip conditionals altogether if cursor position is at pos 0
* Added a test to catch a kernel crash on submission of a language service command where the cursor position is set to 0 in a 0-length buffer

### CODE REVIEW

**Comment by colombod** [comment]
Thank you for this contribution

**Review by colombod — APPROVED** [review]

**Comment by shyamnamboodiripad** [comment]
Thanks for the contribution @cartercanedy! Could you please clarify why the test was excluded from netfx? I see that some other tests in the file were already excluded - but I don't remember why.

**Comment by cartercanedy** [comment]
It looks like the test case is available for both netcore and netfx through Microsoft.DotNet.Interactive.Tests Microsoft.DotNet.Interactive.VisualStudio.Tests. The test uses a CSharpKernel nested in a CompositeKernel, which is unavailable in the latter.

**Comment by shyamnamboodiripad** [comment]
Ah indeed - that makes sense. I was wondering if there was some other reason why the test fails on netfx. Thanks for clarifying.

**Comment by cartercanedy** [comment]
> It looks like the test case is available for both netcore and netfx through Microsoft.DotNet.Interactive.Tests Microsoft.DotNet.Interactive.VisualStudio.Tests. The test uses a CSharpKernel nested in a CompositeKernel, which is unavailable in the latter, so the test project wouldn't compile otherwise

**Pull request merged**
