### PR TITLE
change default HTML formatting to a tree layout rather than a table

### PR DESCRIPTION
**Pull request by jonsequitur**
This addresses #1257.

Here's a preview. Feedback is welcome.

image

### CODE REVIEW

**Review by colombod — APPROVED** [review]

**Comment by bradengc-github** [comment]
How do I change it back to the previous default? I used to get a useful table when displaying a list of C# objects but now it's just a collapsed list of NameSpace.ObjectName.

**Comment by jonsequitur** [comment]
@bradengc-github Once you expand it, is the layout useful? Would expanding it by default help, in other words?

**Comment by bradengc-github** [comment]
> Once you expand it, is the layout useful? Would expanding it by default help, in other words?

Unfortunately not. There's too much vertical scrolling to make that useful. (For an example, a list of objects with 10 properties can only display 3.5 items while expanded even on my large screen.) The table layout where object properties were automatically converted to columns was a much more convenient way to visualize things.

**Comment by DavidZidar** [comment]
@jonsequitur Is there any way to use the old table formatter? This tree layout is only useful for nested objects, for most of my use cases the old table formatter was much better. Now I have to expand every row and can't easily compare rows.

**Comment by jonsequitur** [comment]
For non-homogeneous objects in a sequence, the table formatter produced nested tables. Was that useful at all or is it mainly useful for comparing lists of objects of the same type?

**Comment by DavidZidar** [comment]
I can only speak for myself but I nearly always just print lists of the same type. The old formatter was great imho. Nested tables might be useful, see LINQPad for prior art.

**Pull request merged**
