### PR TITLE
update to new build pools

### PR DESCRIPTION
**Pull request by brettfo**

### CODE REVIEW

**Review by MattGal — CHANGES_REQUESTED** [review]
You also need to update your arcade dependency for this to work.

**Comment by brettfo** [comment]
@MattGal Does the latest Arcade SDK not allow `global.json` to stay on a stable SDK (e.g., 7.0.100)?  The build is failing because an Arcade targets file can't find System.Text.Json 8.0 [here](https://dev.azure.com/dnceng-public/public/_build/results?buildId=163109&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=dad169e2-35ab-5ac6-55b3-7eed7d423255&l=1058).

**Comment by MattGal** [comment]
> @MattGal Does the latest Arcade SDK not allow `global.json` to stay on a stable SDK (e.g., 7.0.100)? The build is failing because an Arcade targets file can't find System.Text.Json 8.0 [here](https://dev.azure.com/dnceng-public/public/_build/results?buildId=163109&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=dad169e2-35ab-5ac6-55b3-7eed7d423255&l=1058).

If you need to stay on a 7.0 SDK, you probably need to move to using the release/7.0 branch of arcade.  I'm going to go port the automatic pool provider stuff there now, in anticipation of folks who do this as well as arcade users who are staying on older arcade in their main branches

**Comment by brettfo** [comment]
@MattGal I updated to release/7.0 of arcade and applied the build pool changes.

**Review by MattGal — APPROVED** [review]
LGTM, that was a fast arcade downgrade!

**Review by MattGal — APPROVED** [review]

**Pull request merged**
