### PR TITLE
Convert JavaScript overview to notebook and update for API changes

### PR DESCRIPTION
**Pull request by kcaswick**
- Convert JavaScript overview to notebook rather than using static pictures of output
- Replace outdated `interactive.csharp` example with `#!share` example
- Minor corrections to other outdated examples and verify each works

1 minor issue remaining - good way to show the final output of dynamic HTML as a cell output... if JavaScript kernel could return text/html it would be easy.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/interactive?pullRequest=2449) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/interactive?pullRequest=2449) before we can accept your contribution.<br/><br/>:x: kcaswick [sign now](https://cla.dotnetfoundation.org/dotnet/interactive?pullRequest=2449)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/interactive?pullRequest=2449) it.</sub>

**Comment by colombod** [comment]
@you have not completed some steps

**Comment by kcaswick** [comment]
> @you have not completed some steps

I'm sorry, I'm unclear what steps are uncompleted. 

Github's sync button did unfortunately do a merge rather than rebase, but since there are no conflicts, I thought that was still consistent with the guidelines and would be cleaned up by the squash & merge.

**Comment by colombod** [comment]
> > @you have not completed some steps
> 
> I'm sorry, I'm unclear what steps are uncompleted.
> 
> Github's sync button did unfortunately do a merge rather than rebase, but since there are no conflicts, I thought that was still consistent with the guidelines and would be cleaned up by the squash & merge.

All good, was stuck on CLA approval

**Comment by jonsequitur** [comment]
Hi @kcaswick. Thanks for the help here! Unfortunately I think I obsoleted some of your changes. We've made some updates to the docs and any feedback you might have would be appreciated. Here's the updated JavaScript docs: https://github.com/dotnet/interactive/blob/main/docs/javascript-overview.md. This is always a work in progress and help on improving it is welcome.

(There's still a backcompat issue for JupyterLab, etc. so this currently assumes the use of the Polyglot Notebooks extension for VS Code, as the screen shots indicate.)

We're moving away from using notebooks as documentation too much because, while the static images are a bit of a pain to maintain, the GitHub viewer doesn't execute JavaScript, so there are a number of examples that can't be shown easily otherwise. We're including notebooks as supplementary samples to accompany the documentation, for people who want to dig in further.

**Comment by colombod** [comment]
@kcaswick I would like to close this PR unless you have comments

**Pull request closed without merging**
