### PR TITLE
add support for net472 in document parsing

### PR DESCRIPTION
**Pull request by colombod**
add net472 to support JakeQuery

### CODE REVIEW

**Comment by JakeRadMSFT** [comment]
This fix worked!

**Comment by brettfo** [comment]
What does adding `net472` add?  Any host that's `net461` and up should be able to load a `netstandard2.0` assembly.

**Comment by JakeRadMSFT** [comment]
> What does adding `net472` add? Any host that's `net461` and up should be able to load a `netstandard2.0` assembly.

@brettfo added you to my learning journey thread on this issue :)

**Comment by jonsequitur** [comment]
This is not needed for now.

**Pull request closed without merging**
